version: 2
jobs:
  build:
    working_directory: ~/akamai-ccu-restclient
    environment:
      TZ: "Asia/Tokyo"
      GO111MODULE: "on"
    docker:
      - image: golang:1.11.5
    steps:
      - checkout
      - run: go test ./...